export const dataShow = [
  {
    id: "XnqM9Zrpg5raQoJvivl8",
    categoryId: "WLCBEkRzCY5H703DUO4o",
    unit: "g",
    createdDate: {
      seconds: 1627293128,
      nanoseconds: 29000000,
    },
    keywords: [
      "c",
      "ca",
      "ca ",
      "ca r",
      "ca ro",
      "ca rot",
      "r",
      "ro",
      "rot",
      "rot ",
      "rot c",
      "rot ca",
    ],
    description: "Nhiều vitamin A",
    discount: 10,
    productImage:
      "https://cdn.tgdd.vn/Files/2019/09/18/1199521/thit-trau-gac-bep-la-gi-an-co-tot-khong--11.jpg",
    productName: "Thịt Bò Gác Bếp",
    price: 29000,
    quantity: 4324,
    updatedDate: {
      seconds: 1628330357,
      nanoseconds: 697000000,
    },
    rating: 4,
  },
  {
    id: "P09oVvIY7kV9wkwvuNzB",
    productName: "Thịt trâu gác bếp",
    rating: 4,
    quantity: 31,
    createdDate: {
      seconds: 1627278142,
      nanoseconds: 452000000,
    },
    description: "Thịt trâu gác bếp Tây Bắc",
    productImage:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQE9FiegypziYE6caFxdQCVFFdmcfw8-6vVfA&usqp=CAU",
    unit: "kg",
    categoryId: "X63OeZXLKAqyVcAm38aT",
    price: 169000,
    discount: 20,
    keywords: [
      "c",
      "ca",
      "cam",
      "cam ",
      "cam c",
      "cam ca",
      "cam can",
      "cam canh",
      "c",
      "ca",
      "can",
      "canh",
      "canh ",
      "canh c",
      "canh ca",
      "canh cam",
    ],
  },
  {
    id: "HHuv99GRSCslKbYXTeuA",
    createdDate: {
      seconds: 1627278094,
      nanoseconds: 965000000,
    },
    rating: 2,
    productImage:
      "http://amthuctaybac.vn/images/stories/virtuemart/product/resized/18079967058_0567dcf308_o_0x250.png",
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    discount: 32,
    unit: "Sản phẩm",
    keywords: [
      "d",
      "du",
      "dui",
      "dui ",
      "dui g",
      "dui ga",
      "dui ga ",
      "dui ga t",
      "dui ga ta",
      "d",
      "du",
      "dui",
      "dui ",
      "dui t",
      "dui ta",
      "dui ta ",
      "dui ta g",
      "dui ta ga",
      "g",
      "ga",
      "ga ",
      "ga d",
      "ga du",
      "ga dui",
      "ga dui ",
      "ga dui t",
      "ga dui ta",
      "g",
      "ga",
      "ga ",
      "ga t",
      "ga ta",
      "ga ta ",
      "ga ta d",
      "ga ta du",
      "ga ta dui",
      "t",
      "ta",
      "ta ",
      "ta d",
      "ta du",
      "ta dui",
      "ta dui ",
      "ta dui g",
      "ta dui ga",
      "t",
      "ta",
      "ta ",
      "ta g",
      "ta ga",
      "ta ga ",
      "ta ga d",
      "ta ga du",
      "ta ga dui",
    ],
    productName: "Mật Ong Nuôi",
    quantity: 41,
    description: "Mật Ong Nuôi, nhiều mật",
    price: 62000,
    updatedDate: {
      seconds: 1629015186,
      nanoseconds: 115000000,
    },
  },
  {
    id: "GuefZDJNIE5mntFypO3E",
    productName: "Thịt lợn gác bếp",
    quantity: 100,
    unit: "Sản phẩm",
    rating: 4,
    categoryId: "ucZK9up2unneAdUkXNRn",
    description: "Xẻ thịt trong ngày",
    createdDate: {
      seconds: 1627278046,
      nanoseconds: 435000000,
    },
    keywords: [
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh mi",
      "banh mi ",
      "banh mi v",
      "banh mi vu",
      "banh mi vun",
      "banh mi vung",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh v",
      "banh vu",
      "banh vun",
      "banh vung",
      "banh vung ",
      "banh vung m",
      "banh vung mi",
      "m",
      "mi",
      "mi ",
      "mi b",
      "mi ba",
      "mi ban",
      "mi banh",
      "mi banh ",
      "mi banh v",
      "mi banh vu",
      "mi banh vun",
      "mi banh vung",
      "m",
      "mi",
      "mi ",
      "mi v",
      "mi vu",
      "mi vun",
      "mi vung",
      "mi vung ",
      "mi vung b",
      "mi vung ba",
      "mi vung ban",
      "mi vung banh",
      "v",
      "vu",
      "vun",
      "vung",
      "vung ",
      "vung b",
      "vung ba",
      "vung ban",
      "vung banh",
      "vung banh ",
      "vung banh m",
      "vung banh mi",
      "v",
      "vu",
      "vun",
      "vung",
      "vung ",
      "vung m",
      "vung mi",
      "vung mi ",
      "vung mi b",
      "vung mi ba",
      "vung mi ban",
      "vung mi banh",
    ],
    price: 24000,
    discount: 5,
    productImage:
      "http://media.dulich24.com.vn/bai-viet/nhung-mon-dac-san-noi-tieng-vung-tay-bac-40090222/34b14f6e-466e-4280-b1f5-df690658b049.jpg",
  },
  {
    id: "E2xNhX5DumicnQoD6rIw",
    rating: 4,
    productImage:
      "http://media.dulich24.com.vn/bai-viet/6-dac-san-lai-chau-nen-thu-tren-duong-du-lich-45105135/6-dac-san-lai-chau-nen-thu-tren-duong-du-lich-1.jpg",
    keywords: ["q", "qu", "qua", "quat"],
    description: "Đặc sản miền núi",
    discount: 18,
    unit: "Quả",
    productName: "Lợn cắp nách",
    categoryId: "X63OeZXLKAqyVcAm38aT",
    quantity: 100,
    price: 88000,
    createdDate: {
      seconds: 1627277982,
      nanoseconds: 606000000,
    },
  },
  {
    id: "iYzD7lXqxYgiu1imSshQ",
    rating: 4,
    discount: 15,
    productName: "Bê mộc châu",
    createdDate: {
      seconds: 1627277867,
      nanoseconds: 53000000,
    },
    keywords: [
      "c",
      "ch",
      "chu",
      "chuo",
      "chuoi",
      "chuoi ",
      "chuoi t",
      "chuoi ti",
      "chuoi tie",
      "chuoi tieu",
      "t",
      "ti",
      "tie",
      "tieu",
      "tieu ",
      "tieu c",
      "tieu ch",
      "tieu chu",
      "tieu chuo",
      "tieu chuoi",
    ],
    unit: "Quả",
    categoryId: "X63OeZXLKAqyVcAm38aT",
    description: "Số lượng lớn",
    price: 88000,
    quantity: 21,
    productImage:
      "http://media.dulich24.com.vn/diemden/cao-nguyen-moc-chau-son-la-3356/cao-nguyen-moc-chau-11.jpg",
  },
  {
    id: "Wjc8fbJkpSRIpBUi9LgD",
    unit: "kg",
    productName: "Sâu chít điện biên",
    rating: 3,
    discount: 80,
    description: "Nuôi môi trường nước ngọt",
    keywords: [
      "c",
      "ca",
      "ca ",
      "ca n",
      "ca nu",
      "n",
      "nu",
      "nu ",
      "nu c",
      "nu ca",
    ],
    quantity: 31,
    createdDate: {
      seconds: 1627277798,
      nanoseconds: 316000000,
    },
    productImage:
      "http://media.dulich24.com.vn/bai-viet/nhung-mon-dac-san-noi-tieng-vung-tay-bac-40090222/74fa5b92-9517-4b6b-9965-a2007795cb1f.jpg",
    updatedDate: {
      seconds: 1627277803,
      nanoseconds: 948000000,
    },
    price: 46000,
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
  },
  {
    id: "TNqaxRJ6uSsS6evoppLT",
    productImage:
      "http://media.dulich24.com.vn/bai-viet/6-dac-san-lai-chau-nen-thu-tren-duong-du-lich-45105135/6-dac-san-lai-chau-nen-thu-tren-duong-du-lich-2.jpg",
    description: "Xẻ thịt trong ngày",
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    price: 78000,
    quantity: 100,
    keywords: [
      "b",
      "ba",
      "bap",
      "bap ",
      "bap b",
      "bap bo",
      "b",
      "bo",
      "bo ",
      "bo b",
      "bo ba",
      "bo bap",
    ],
    unit: "kg",
    rating: 3,
    discount: 10,
    productName: "Cá bống vùi tro",
    createdDate: {
      seconds: 1627277746,
      nanoseconds: 648000000,
    },
  },
  {
    id: "wcwqXeBlTnuP1uUQknRO",
    createdDate: {
      seconds: 1627277697,
      nanoseconds: 81000000,
    },
    description: "Táo chua ngâm rượu",
    discount: 60,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/fr6.jpg?alt=media&token=1c26ccce-8a61-47c4-9da4-915a24fc2f37",
    productName: "Táo tàu",
    unit: "kg",
    keywords: [
      "t",
      "ta",
      "tao",
      "tao ",
      "tao t",
      "tao ta",
      "tao tau",
      "t",
      "ta",
      "tau",
      "tau ",
      "tau t",
      "tau ta",
      "tau tao",
    ],
    rating: 4,
    quantity: 21,
    categoryId: "X63OeZXLKAqyVcAm38aT",
    price: 70000,
  },
  {
    id: "OZeQsBVnK1xiWzKHaTWr",
    description: "Gừng hòa quyện cùng bột bánh",
    price: 37000,
    discount: 2,
    keywords: [
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh mi",
      "banh mi ",
      "banh mi g",
      "banh mi gu",
      "banh mi gun",
      "banh mi gung",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh g",
      "banh gu",
      "banh gun",
      "banh gung",
      "banh gung ",
      "banh gung m",
      "banh gung mi",
      "m",
      "mi",
      "mi ",
      "mi b",
      "mi ba",
      "mi ban",
      "mi banh",
      "mi banh ",
      "mi banh g",
      "mi banh gu",
      "mi banh gun",
      "mi banh gung",
      "m",
      "mi",
      "mi ",
      "mi g",
      "mi gu",
      "mi gun",
      "mi gung",
      "mi gung ",
      "mi gung b",
      "mi gung ba",
      "mi gung ban",
      "mi gung banh",
      "g",
      "gu",
      "gun",
      "gung",
      "gung ",
      "gung b",
      "gung ba",
      "gung ban",
      "gung banh",
      "gung banh ",
      "gung banh m",
      "gung banh mi",
      "g",
      "gu",
      "gun",
      "gung",
      "gung ",
      "gung m",
      "gung mi",
      "gung mi ",
      "gung mi b",
      "gung mi ba",
      "gung mi ban",
      "gung mi banh",
    ],
    productName: "Bánh mì gừng",
    rating: 2,
    quantity: 100,
    unit: "Sản phẩm",
    categoryId: "ucZK9up2unneAdUkXNRn",
    createdDate: {
      seconds: 1627277641,
      nanoseconds: 144000000,
    },
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/b4.jpg?alt=media&token=a45aaf43-59f4-4296-a93c-4d8d427b1de1",
  },
  {
    id: "Hr0OdfA2CPJTPcIUW8JA",
    unit: "kg",
    price: 67000,
    discount: 32,
    keywords: [
      "d",
      "da",
      "dau",
      "dau ",
      "dau b",
      "dau ba",
      "dau bap",
      "b",
      "ba",
      "bap",
      "bap ",
      "bap d",
      "bap da",
      "bap dau",
    ],
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v21.jpg?alt=media&token=773ba1fa-8c9d-42e6-a396-8d7a76b4b54b",
    quantity: 41,
    createdDate: {
      seconds: 1627277594,
      nanoseconds: 808000000,
    },
    productName: "Đậu bắp",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    description: "Phù hợp món nướng",
    rating: 3,
  },
  {
    id: "dYWGsGiUWNvjzmycDJR4",
    createdDate: {
      seconds: 1627277554,
      nanoseconds: 841000000,
    },
    keywords: [
      "c",
      "cu",
      "cui",
      "cui ",
      "cui d",
      "cui du",
      "cui dua",
      "d",
      "du",
      "dua",
      "dua ",
      "dua c",
      "dua cu",
      "dua cui",
    ],
    productName: "Cùi dừa",
    price: 71000,
    categoryId: "wVaMcDH4yni65ls9aY3C",
    quantity: 10,
    description: "Nạo từ những quả dừa",
    discount: 20,
    rating: 4,
    unit: "Sản phẩm",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/o3.jpg?alt=media&token=8e62563d-b8c1-4851-aae2-951f438b4bf8",
  },
  {
    id: "G6rpXqqC8SmWdWzRISYs",
    productName: "Hạt đỗ",
    rating: 4,
    categoryId: "wVaMcDH4yni65ls9aY3C",
    createdDate: {
      seconds: 1627277519,
      nanoseconds: 175000000,
    },
    keywords: [
      "h",
      "ha",
      "hat",
      "hat ",
      "hat d",
      "hat do",
      "d",
      "do",
      "do ",
      "do h",
      "do ha",
      "do hat",
    ],
    unit: "Sản phẩm",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/o9.jpg?alt=media&token=e4a2a036-dcd7-4781-844e-3fc94c6ac06b",
    discount: 60,
    description: "Đỗ lê men",
    price: 14000,
    quantity: 100,
  },
  {
    id: "1Cfjz85fhM6TIw9hGdPw",
    price: 134000,
    quantity: 2,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/05.jpg?alt=media&token=1577aaac-a756-45a4-b800-31961cf3f86a",
    createdDate: {
      seconds: 1627277474,
      nanoseconds: 538000000,
    },
    discount: 50,
    productName: "Cá chuồn 123",
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    description: "Cá ngoài biển mặn 123",
    unit: "g",
    keywords: [
      "c",

      "ca",
      "ca ",
      "ca c",
      "ca ch",
      "ca chu",
      "ca chuo",
      "ca chuon",
      "c",
      "ch",
      "chu",
      "chuo",
      "chuon",
      "chuon ",
      "chuon c",
      "chuon ca",
    ],
    rating: 3,
  },
  {
    id: "L2PfMKuT7Bwaa4DQbOcY",
    discount: 20,
    description: "Thịt bò hảo hạng",
    rating: 2,
    price: 89000,
    productName: "Xườn bò",
    unit: "g",
    quantity: 99,
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/meat3.jpg?alt=media&token=f3597b41-cd1c-4d54-b497-9a69ef450a48",
    createdDate: {
      seconds: 1627277429,
      nanoseconds: 304000000,
    },
    keywords: [
      "x",
      "xu",
      "xuo",
      "xuon",
      "xuon ",
      "xuon b",
      "xuon bo",
      "b",
      "bo",
      "bo ",
      "bo x",
      "bo xu",
      "bo xuo",
      "bo xuon",
    ],
  },
  {
    id: "WXzW6oozaokDarx3LPKO",
    createdDate: {
      seconds: 1627277374,
      nanoseconds: 834000000,
    },
    price: 57000,
    unit: "Sản phẩm",
    rating: 2,
    productName: "Tỏi nghiền",
    description: "Gia vị tỏi ớt",
    quantity: 100,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s9.jpg?alt=media&token=5859cce4-1cd3-4df3-b9b9-51db221b023a",
    discount: 60,
    categoryId: "D12YC358aOe71ZVhrdOf",
    keywords: [
      "t",
      "to",
      "toi",
      "toi ",
      "toi n",
      "toi ng",
      "toi ngh",
      "toi nghi",
      "toi nghie",
      "toi nghien",
      "n",
      "ng",
      "ngh",
      "nghi",
      "nghie",
      "nghien",
      "nghien ",
      "nghien t",
      "nghien to",
      "nghien toi",
    ],
  },
  {
    id: "lTqE7bwJ7ne17NHQzC6I",
    keywords: [
      "s",
      "su",
      "sua",
      "sua ",
      "sua d",
      "sua du",
      "sua dua",
      "d",
      "du",
      "dua",
      "dua ",
      "dua s",
      "dua su",
      "dua sua",
    ],
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s12.jpg?alt=media&token=86de0a16-3f36-444f-967c-5ddcd5cc7b64",
    price: 51000,
    categoryId: "WLCBEkRzCY5H703DUO4o",
    productName: "Sữa dừa",
    unit: "Sản phẩm",
    quantity: 31,
    createdDate: {
      seconds: 1627277328,
      nanoseconds: 941000000,
    },
    description: "Nguyên chất 100% tự nhiên",
    rating: 2,
    discount: 32,
  },
  {
    id: "FA2WgNwov3ixt7cBFega",
    createdDate: {
      seconds: 1627277266,
      nanoseconds: 297000000,
    },
    unit: "kg",
    price: 27000,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v9.jpg?alt=media&token=5a4a44c3-dad9-4276-9cf9-3568992986fa",
    discount: 15,
    description: "Rau được trồng hưu cơ",
    rating: 4,
    quantity: 100,
    productName: "Cải lơ",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    keywords: [
      "c",
      "ca",
      "cai",
      "cai ",
      "cai l",
      "cai lo",
      "l",
      "lo",
      "lo ",
      "lo c",
      "lo ca",
      "lo cai",
    ],
  },
  {
    id: "j8bu2hpYygc572Zwe3c5",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v17.jpg?alt=media&token=e53d6797-5f67-4e20-b3c6-74e21b032dfb",
    price: 123000,
    keywords: [
      "n",
      "ng",
      "ngo",
      "ngo ",
      "ngo n",
      "ngo ne",
      "ngo nep",
      "n",
      "ne",
      "nep",
      "nep ",
      "nep n",
      "nep ng",
      "nep ngo",
    ],
    createdDate: {
      seconds: 1627276925,
      nanoseconds: 246000000,
    },
    unit: "kg",
    quantity: 21,
    discount: 71,
    rating: 3,
    description: "Ngô nếp số lượng ít",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    productName: "Ngô nếp",
  },
  {
    id: "8zVFEm5w5Ist0tyLuv34",
    rating: 2,
    price: 33000,
    unit: "Sản phẩm",
    productName: "Bánh tròn",
    createdDate: {
      seconds: 1627276839,
      nanoseconds: 815000000,
    },
    quantity: 21,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/b5.jpg?alt=media&token=09887fa4-41fb-4b0a-8ade-af59500de884",
    discount: 20,
    categoryId: "ucZK9up2unneAdUkXNRn",
    description: "Bánh hình trăng tròn",
    keywords: [
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh t",
      "banh tr",
      "banh tro",
      "banh tron",
      "t",
      "tr",
      "tro",
      "tron",
      "tron ",
      "tron b",
      "tron ba",
      "tron ban",
      "tron banh",
    ],
  },
  {
    id: "mOoUahfS8s7ufiJE7TrM",
    price: 26000,
    unit: "kg",
    quantity: 31,
    rating: 4,
    keywords: [
      "b",
      "ba",
      "ba ",
      "ba c",
      "ba ch",
      "ba chi",
      "c",
      "ch",
      "chi",
      "chi ",
      "chi b",
      "chi ba",
    ],
    description: "Thịt đông lạnh",
    discount: 21,
    createdDate: {
      seconds: 1627276800,
      nanoseconds: 269000000,
    },
    productName: "Ba chỉ",
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/meat_05-360x360.jpg?alt=media&token=5f081e4f-7036-4608-ab8b-4c609a3e17f5",
  },
  {
    id: "g6As5iUetpW2q7yuItud",
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    quantity: 21,
    rating: 3,
    productName: "Cá chíp",
    unit: "g",
    description: "Đánh bắt xa bờ vùng biển phía Đông",
    price: 120000,
    keywords: [
      "c",
      "ca",
      "ca ",
      "ca c",
      "ca ch",
      "ca chi",
      "ca chip",
      "c",
      "ch",
      "chi",
      "chip",
      "chip ",
      "chip c",
      "chip ca",
    ],
    discount: 15,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/01.jpg?alt=media&token=5a678293-85bc-472c-984e-8015f150933d",
    createdDate: {
      seconds: 1627276766,
      nanoseconds: 401000000,
    },
  },
  {
    id: "P0ZoZr5By4mUvIkw6Ut0",
    categoryId: "X63OeZXLKAqyVcAm38aT",
    description: "Chuối vàng trồng tự nhiên",
    productName: "Chuối ta",
    price: 77000,
    quantity: 31,
    createdDate: {
      seconds: 1627276688,
      nanoseconds: 732000000,
    },
    unit: "Quả",
    keywords: [
      "c",
      "ch",
      "chu",
      "chuo",
      "chuoi",
      "chuoi ",
      "chuoi t",
      "chuoi ta",
      "t",
      "ta",
      "ta ",
      "ta c",
      "ta ch",
      "ta chu",
      "ta chuo",
      "ta chuoi",
    ],
    rating: 2,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/fr1.jpg?alt=media&token=05d94340-702f-4c68-a007-e6d560964680",
    discount: 32,
  },
  {
    id: "abqd3lvts3Gw8pVuL5Fw",
    discount: 80,
    createdDate: {
      seconds: 1627274878,
      nanoseconds: 955000000,
    },
    keywords: [
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh mi",
      "banh mi ",
      "banh mi m",
      "banh mi ma",
      "banh mi mat",
      "banh mi mat ",
      "banh mi mat o",
      "banh mi mat on",
      "banh mi mat ong",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh mi",
      "banh mi ",
      "banh mi o",
      "banh mi on",
      "banh mi ong",
      "banh mi ong ",
      "banh mi ong m",
      "banh mi ong ma",
      "banh mi ong mat",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh ma",
      "banh mat",
      "banh mat ",
      "banh mat m",
      "banh mat mi",
      "banh mat mi ",
      "banh mat mi o",
      "banh mat mi on",
      "banh mat mi ong",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh ma",
      "banh mat",
      "banh mat ",
      "banh mat o",
      "banh mat on",
      "banh mat ong",
      "banh mat ong ",
      "banh mat ong m",
      "banh mat ong mi",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh o",
      "banh on",
      "banh ong",
      "banh ong ",
      "banh ong m",
      "banh ong mi",
      "banh ong mi ",
      "banh ong mi m",
      "banh ong mi ma",
      "banh ong mi mat",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh o",
      "banh on",
      "banh ong",
      "banh ong ",
      "banh ong m",
      "banh ong ma",
      "banh ong mat",
      "banh ong mat ",
      "banh ong mat m",
      "banh ong mat mi",
      "m",
      "mi",
      "mi ",
      "mi b",
      "mi ba",
      "mi ban",
      "mi banh",
      "mi banh ",
      "mi banh m",
      "mi banh ma",
      "mi banh mat",
      "mi banh mat ",
      "mi banh mat o",
      "mi banh mat on",
      "mi banh mat ong",
      "m",
      "mi",
      "mi ",
      "mi b",
      "mi ba",
      "mi ban",
      "mi banh",
      "mi banh ",
      "mi banh o",
      "mi banh on",
      "mi banh ong",
      "mi banh ong ",
      "mi banh ong m",
      "mi banh ong ma",
      "mi banh ong mat",
      "m",
      "mi",
      "mi ",
      "mi m",
      "mi ma",
      "mi mat",
      "mi mat ",
      "mi mat b",
      "mi mat ba",
      "mi mat ban",
      "mi mat banh",
      "mi mat banh ",
      "mi mat banh o",
      "mi mat banh on",
      "mi mat banh ong",
      "m",
      "mi",
      "mi ",
      "mi m",
      "mi ma",
      "mi mat",
      "mi mat ",
      "mi mat o",
      "mi mat on",
      "mi mat ong",
      "mi mat ong ",
      "mi mat ong b",
      "mi mat ong ba",
      "mi mat ong ban",
      "mi mat ong banh",
      "m",
      "mi",
      "mi ",
      "mi o",
      "mi on",
      "mi ong",
      "mi ong ",
      "mi ong b",
      "mi ong ba",
      "mi ong ban",
      "mi ong banh",
      "mi ong banh ",
      "mi ong banh m",
      "mi ong banh ma",
      "mi ong banh mat",
      "m",
      "mi",
      "mi ",
      "mi o",
      "mi on",
      "mi ong",
      "mi ong ",
      "mi ong m",
      "mi ong ma",
      "mi ong mat",
      "mi ong mat ",
      "mi ong mat b",
      "mi ong mat ba",
      "mi ong mat ban",
      "mi ong mat banh",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat b",
      "mat ba",
      "mat ban",
      "mat banh",
      "mat banh ",
      "mat banh m",
      "mat banh mi",
      "mat banh mi ",
      "mat banh mi o",
      "mat banh mi on",
      "mat banh mi ong",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat b",
      "mat ba",
      "mat ban",
      "mat banh",
      "mat banh ",
      "mat banh o",
      "mat banh on",
      "mat banh ong",
      "mat banh ong ",
      "mat banh ong m",
      "mat banh ong mi",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat m",
      "mat mi",
      "mat mi ",
      "mat mi b",
      "mat mi ba",
      "mat mi ban",
      "mat mi banh",
      "mat mi banh ",
      "mat mi banh o",
      "mat mi banh on",
      "mat mi banh ong",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat m",
      "mat mi",
      "mat mi ",
      "mat mi o",
      "mat mi on",
      "mat mi ong",
      "mat mi ong ",
      "mat mi ong b",
      "mat mi ong ba",
      "mat mi ong ban",
      "mat mi ong banh",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat o",
      "mat on",
      "mat ong",
      "mat ong ",
      "mat ong b",
      "mat ong ba",
      "mat ong ban",
      "mat ong banh",
      "mat ong banh ",
      "mat ong banh m",
      "mat ong banh mi",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat o",
      "mat on",
      "mat ong",
      "mat ong ",
      "mat ong m",
      "mat ong mi",
      "mat ong mi ",
      "mat ong mi b",
      "mat ong mi ba",
      "mat ong mi ban",
      "mat ong mi banh",
      "o",
      "on",
      "ong",
      "ong ",
      "ong b",
      "ong ba",
      "ong ban",
      "ong banh",
      "ong banh ",
      "ong banh m",
      "ong banh mi",
      "ong banh mi ",
      "ong banh mi m",
      "ong banh mi ma",
      "ong banh mi mat",
      "o",
      "on",
      "ong",
      "ong ",
      "ong b",
      "ong ba",
      "ong ban",
      "ong banh",
      "ong banh ",
      "ong banh m",
      "ong banh ma",
      "ong banh mat",
      "ong banh mat ",
      "ong banh mat m",
      "ong banh mat mi",
      "o",
      "on",
      "ong",
      "ong ",
      "ong m",
      "ong mi",
      "ong mi ",
      "ong mi b",
      "ong mi ba",
      "ong mi ban",
      "ong mi banh",
      "ong mi banh ",
      "ong mi banh m",
      "ong mi banh ma",
      "ong mi banh mat",
      "o",
      "on",
      "ong",
      "ong ",
      "ong m",
      "ong mi",
      "ong mi ",
      "ong mi m",
      "ong mi ma",
      "ong mi mat",
      "ong mi mat ",
      "ong mi mat b",
      "ong mi mat ba",
      "ong mi mat ban",
      "ong mi mat banh",
      "o",
      "on",
      "ong",
      "ong ",
      "ong m",
      "ong ma",
      "ong mat",
      "ong mat ",
      "ong mat b",
      "ong mat ba",
      "ong mat ban",
      "ong mat banh",
      "ong mat banh ",
      "ong mat banh m",
      "ong mat banh mi",
      "o",
      "on",
      "ong",
      "ong ",
      "ong m",
      "ong ma",
      "ong mat",
      "ong mat ",
      "ong mat m",
      "ong mat mi",
      "ong mat mi ",
      "ong mat mi b",
      "ong mat mi ba",
      "ong mat mi ban",
      "ong mat mi banh",
    ],
    description: "Mật ong từ tự nhiên",
    unit: "Sản phẩm",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/b8.jpg?alt=media&token=f3a8f27b-c0ba-450f-bd22-b822340e6d03",
    productName: "Bánh mì mật ong",
    quantity: 10,
    rating: 4,
    categoryId: "ucZK9up2unneAdUkXNRn",
    price: 34000,
    updatedDate: {
      seconds: 1627276698,
      nanoseconds: 532000000,
    },
  },
  {
    id: "6fA7A6NA2r3KsTWXNW3A",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v18.jpg?alt=media&token=1494712c-f52e-46bc-ada3-3e63f2aab630",
    quantity: 100,
    unit: "kg",
    price: 77800,
    productName: "Dưa chuột",
    keywords: [
      "d",
      "du",
      "dua",
      "dua ",
      "dua c",
      "dua ch",
      "dua chu",
      "dua chuo",
      "dua chuot",
      "c",
      "ch",
      "chu",
      "chuo",
      "chuot",
      "chuot ",
      "chuot d",
      "chuot du",
      "chuot dua",
    ],
    discount: 32,
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    rating: 4,
    description: "Dưa sạch, thơm ngon",
    createdDate: {
      seconds: 1627274820,
      nanoseconds: 648000000,
    },
  },
  {
    id: "OudE30t9g1IqXiNXFRAy",
    price: 140000,
    keywords: [
      "g",
      "ga",
      "ga ",
      "ga t",
      "ga ta",
      "ga tay",
      "ga tay ",
      "ga tay n",
      "ga tay ng",
      "ga tay ngu",
      "ga tay nguy",
      "ga tay nguye",
      "ga tay nguyen",
      "ga tay nguyen ",
      "ga tay nguyen c",
      "ga tay nguyen co",
      "ga tay nguyen con",
      "g",
      "ga",
      "ga ",
      "ga t",
      "ga ta",
      "ga tay",
      "ga tay ",
      "ga tay c",
      "ga tay co",
      "ga tay con",
      "ga tay con ",
      "ga tay con n",
      "ga tay con ng",
      "ga tay con ngu",
      "ga tay con nguy",
      "ga tay con nguye",
      "ga tay con nguyen",
      "g",
      "ga",
      "ga ",
      "ga n",
      "ga ng",
      "ga ngu",
      "ga nguy",
      "ga nguye",
      "ga nguyen",
      "ga nguyen ",
      "ga nguyen t",
      "ga nguyen ta",
      "ga nguyen tay",
      "ga nguyen tay ",
      "ga nguyen tay c",
      "ga nguyen tay co",
      "ga nguyen tay con",
      "g",
      "ga",
      "ga ",
      "ga n",
      "ga ng",
      "ga ngu",
      "ga nguy",
      "ga nguye",
      "ga nguyen",
      "ga nguyen ",
      "ga nguyen c",
      "ga nguyen co",
      "ga nguyen con",
      "ga nguyen con ",
      "ga nguyen con t",
      "ga nguyen con ta",
      "ga nguyen con tay",
      "g",
      "ga",
      "ga ",
      "ga c",
      "ga co",
      "ga con",
      "ga con ",
      "ga con t",
      "ga con ta",
      "ga con tay",
      "ga con tay ",
      "ga con tay n",
      "ga con tay ng",
      "ga con tay ngu",
      "ga con tay nguy",
      "ga con tay nguye",
      "ga con tay nguyen",
      "g",
      "ga",
      "ga ",
      "ga c",
      "ga co",
      "ga con",
      "ga con ",
      "ga con n",
      "ga con ng",
      "ga con ngu",
      "ga con nguy",
      "ga con nguye",
      "ga con nguyen",
      "ga con nguyen ",
      "ga con nguyen t",
      "ga con nguyen ta",
      "ga con nguyen tay",
      "t",
      "ta",
      "tay",
      "tay ",
      "tay g",
      "tay ga",
      "tay ga ",
      "tay ga n",
      "tay ga ng",
      "tay ga ngu",
      "tay ga nguy",
      "tay ga nguye",
      "tay ga nguyen",
      "tay ga nguyen ",
      "tay ga nguyen c",
      "tay ga nguyen co",
      "tay ga nguyen con",
      "t",
      "ta",
      "tay",
      "tay ",
      "tay g",
      "tay ga",
      "tay ga ",
      "tay ga c",
      "tay ga co",
      "tay ga con",
      "tay ga con ",
      "tay ga con n",
      "tay ga con ng",
      "tay ga con ngu",
      "tay ga con nguy",
      "tay ga con nguye",
      "tay ga con nguyen",
      "t",
      "ta",
      "tay",
      "tay ",
      "tay n",
      "tay ng",
      "tay ngu",
      "tay nguy",
      "tay nguye",
      "tay nguyen",
      "tay nguyen ",
      "tay nguyen g",
      "tay nguyen ga",
      "tay nguyen ga ",
      "tay nguyen ga c",
      "tay nguyen ga co",
      "tay nguyen ga con",
      "t",
      "ta",
      "tay",
      "tay ",
      "tay n",
      "tay ng",
      "tay ngu",
      "tay nguy",
      "tay nguye",
      "tay nguyen",
      "tay nguyen ",
      "tay nguyen c",
      "tay nguyen co",
      "tay nguyen con",
      "tay nguyen con ",
      "tay nguyen con g",
      "tay nguyen con ga",
      "t",
      "ta",
      "tay",
      "tay ",
      "tay c",
      "tay co",
      "tay con",
      "tay con ",
      "tay con g",
      "tay con ga",
      "tay con ga ",
      "tay con ga n",
      "tay con ga ng",
      "tay con ga ngu",
      "tay con ga nguy",
      "tay con ga nguye",
      "tay con ga nguyen",
      "t",
      "ta",
      "tay",
      "tay ",
      "tay c",
      "tay co",
      "tay con",
      "tay con ",
      "tay con n",
      "tay con ng",
      "tay con ngu",
      "tay con nguy",
      "tay con nguye",
      "tay con nguyen",
      "tay con nguyen ",
      "tay con nguyen g",
      "tay con nguyen ga",
      "n",
      "ng",
      "ngu",
      "nguy",
      "nguye",
      "nguyen",
      "nguyen ",
      "nguyen g",
      "nguyen ga",
      "nguyen ga ",
      "nguyen ga t",
      "nguyen ga ta",
      "nguyen ga tay",
      "nguyen ga tay ",
      "nguyen ga tay c",
      "nguyen ga tay co",
      "nguyen ga tay con",
      "n",
      "ng",
      "ngu",
      "nguy",
      "nguye",
      "nguyen",
      "nguyen ",
      "nguyen g",
      "nguyen ga",
      "nguyen ga ",
      "nguyen ga c",
      "nguyen ga co",
      "nguyen ga con",
      "nguyen ga con ",
      "nguyen ga con t",
      "nguyen ga con ta",
      "nguyen ga con tay",
      "n",
      "ng",
      "ngu",
      "nguy",
      "nguye",
      "nguyen",
      "nguyen ",
      "nguyen t",
      "nguyen ta",
      "nguyen tay",
      "nguyen tay ",
      "nguyen tay g",
      "nguyen tay ga",
      "nguyen tay ga ",
      "nguyen tay ga c",
      "nguyen tay ga co",
      "nguyen tay ga con",
      "n",
      "ng",
      "ngu",
      "nguy",
      "nguye",
      "nguyen",
      "nguyen ",
      "nguyen t",
      "nguyen ta",
      "nguyen tay",
      "nguyen tay ",
      "nguyen tay c",
      "nguyen tay co",
      "nguyen tay con",
      "nguyen tay con ",
      "nguyen tay con g",
      "nguyen tay con ga",
      "n",
      "ng",
      "ngu",
      "nguy",
      "nguye",
      "nguyen",
      "nguyen ",
      "nguyen c",
      "nguyen co",
      "nguyen con",
      "nguyen con ",
      "nguyen con g",
      "nguyen con ga",
      "nguyen con ga ",
      "nguyen con ga t",
      "nguyen con ga ta",
      "nguyen con ga tay",
      "n",
      "ng",
      "ngu",
      "nguy",
      "nguye",
      "nguyen",
      "nguyen ",
      "nguyen c",
      "nguyen co",
      "nguyen con",
      "nguyen con ",
      "nguyen con t",
      "nguyen con ta",
      "nguyen con tay",
      "nguyen con tay ",
      "nguyen con tay g",
      "nguyen con tay ga",
      "c",
      "co",
      "con",
      "con ",
      "con g",
      "con ga",
      "con ga ",
      "con ga t",
      "con ga ta",
      "con ga tay",
      "con ga tay ",
      "con ga tay n",
      "con ga tay ng",
      "con ga tay ngu",
      "con ga tay nguy",
      "con ga tay nguye",
      "con ga tay nguyen",
      "c",
      "co",
      "con",
      "con ",
      "con g",
      "con ga",
      "con ga ",
      "con ga n",
      "con ga ng",
      "con ga ngu",
      "con ga nguy",
      "con ga nguye",
      "con ga nguyen",
      "con ga nguyen ",
      "con ga nguyen t",
      "con ga nguyen ta",
      "con ga nguyen tay",
      "c",
      "co",
      "con",
      "con ",
      "con t",
      "con ta",
      "con tay",
      "con tay ",
      "con tay g",
      "con tay ga",
      "con tay ga ",
      "con tay ga n",
      "con tay ga ng",
      "con tay ga ngu",
      "con tay ga nguy",
      "con tay ga nguye",
      "con tay ga nguyen",
      "c",
      "co",
      "con",
      "con ",
      "con t",
      "con ta",
      "con tay",
      "con tay ",
      "con tay n",
      "con tay ng",
      "con tay ngu",
      "con tay nguy",
      "con tay nguye",
      "con tay nguyen",
      "con tay nguyen ",
      "con tay nguyen g",
      "con tay nguyen ga",
      "c",
      "co",
      "con",
      "con ",
      "con n",
      "con ng",
      "con ngu",
      "con nguy",
      "con nguye",
      "con nguyen",
      "con nguyen ",
      "con nguyen g",
      "con nguyen ga",
      "con nguyen ga ",
      "con nguyen ga t",
      "con nguyen ga ta",
      "con nguyen ga tay",
      "c",
      "co",
      "con",
      "con ",
      "con n",
      "con ng",
      "con ngu",
      "con nguy",
      "con nguye",
      "con nguyen",
      "con nguyen ",
      "con nguyen t",
      "con nguyen ta",
      "con nguyen tay",
      "con nguyen tay ",
      "con nguyen tay g",
      "con nguyen tay ga",
    ],
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/Product9.jpg?alt=media&token=4b710dd8-f0c6-454a-a3b0-d90738ba0226",
    unit: "Sản phẩm",
    createdDate: {
      seconds: 1627274754,
      nanoseconds: 833000000,
    },
    description: "Siêu to, đầy đặn",
    productName: "Gà tây nguyên con",
    discount: 21,
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    quantity: 10,
    rating: 2,
  },
  {
    id: "XzReL5kEqRoKy4ZlYAsg",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/03.jpg?alt=media&token=458255ac-83c4-4413-b3e5-e7577737d797",
    keywords: [
      "c",
      "ca",
      "ca ",
      "ca h",
      "ca ho",
      "h",
      "ho",
      "ho ",
      "ho c",
      "ho ca",
    ],
    price: 310000,
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    discount: 21,
    quantity: 100,
    rating: 3,
    productName: "Cá hổ",
    description: "Vùng biển Việt Nam",
    unit: "kg",
    createdDate: {
      seconds: 1627274674,
      nanoseconds: 465000000,
    },
  },
  {
    id: "wpSAD0JDgu5w1Cv3wTar",
    description: "Sản xuất số lượng lớn",
    quantity: 100,
    price: 2000,
    unit: "Sản phẩm",
    productName: "Bánh mì vuông",
    keywords: [
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh mi",
      "banh mi ",
      "banh mi v",
      "banh mi vu",
      "banh mi vuo",
      "banh mi vuon",
      "banh mi vuong",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh v",
      "banh vu",
      "banh vuo",
      "banh vuon",
      "banh vuong",
      "banh vuong ",
      "banh vuong m",
      "banh vuong mi",
      "m",
      "mi",
      "mi ",
      "mi b",
      "mi ba",
      "mi ban",
      "mi banh",
      "mi banh ",
      "mi banh v",
      "mi banh vu",
      "mi banh vuo",
      "mi banh vuon",
      "mi banh vuong",
      "m",
      "mi",
      "mi ",
      "mi v",
      "mi vu",
      "mi vuo",
      "mi vuon",
      "mi vuong",
      "mi vuong ",
      "mi vuong b",
      "mi vuong ba",
      "mi vuong ban",
      "mi vuong banh",
      "v",
      "vu",
      "vuo",
      "vuon",
      "vuong",
      "vuong ",
      "vuong b",
      "vuong ba",
      "vuong ban",
      "vuong banh",
      "vuong banh ",
      "vuong banh m",
      "vuong banh mi",
      "v",
      "vu",
      "vuo",
      "vuon",
      "vuong",
      "vuong ",
      "vuong m",
      "vuong mi",
      "vuong mi ",
      "vuong mi b",
      "vuong mi ba",
      "vuong mi ban",
      "vuong mi banh",
    ],
    categoryId: "ucZK9up2unneAdUkXNRn",
    discount: 15,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/b1.jpg?alt=media&token=e384d8f0-e020-46e6-996c-f64be4ee8430",
    createdDate: {
      seconds: 1627273890,
      nanoseconds: 771000000,
    },
    rating: 3,
  },
  {
    id: "oXAVwRuLd89ybEFpgr51",
    quantity: 100,
    rating: 3,
    keywords: [
      "s",
      "so",
      "sot",
      "sot ",
      "sot t",
      "sot ta",
      "sot tao",
      "t",
      "ta",
      "tao",
      "tao ",
      "tao s",
      "tao so",
      "tao sot",
    ],
    description: "Phù hợp mới các loại đồ ngọt",
    unit: "Sản phẩm",
    discount: 7,
    createdDate: {
      seconds: 1627273623,
      nanoseconds: 270000000,
    },
    categoryId: "D12YC358aOe71ZVhrdOf",
    productName: "Sốt táo",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s1.jpg?alt=media&token=07321622-c576-4e54-bd25-9ae44f44548f",
    price: 42000,
  },
  {
    id: "8c2zTt22CnQcE3Wz5tfW",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v11.jpg?alt=media&token=41161c80-0610-41a6-ae72-c0455b52cabf",
    unit: "g",
    rating: 3,
    description: "Đỗ thu hoạch trong ngày",
    keywords: [
      "r",
      "ra",
      "rau",
      "rau ",
      "rau d",
      "rau do",
      "d",
      "do",
      "do ",
      "do r",
      "do ra",
      "do rau",
    ],
    discount: 10,
    productName: "Rau đỗ",
    quantity: 21,
    createdDate: {
      seconds: 1627273549,
      nanoseconds: 220000000,
    },
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    price: 5000,
  },
  {
    id: "yeNCseatNyvIqXT2QkqN",
    keywords: [
      "g",
      "ga",
      "gao",
      "gao ",
      "gao t",
      "gao te",
      "t",
      "te",
      "te ",
      "te g",
      "te ga",
      "te gao",
    ],
    productName: "Gạo tẻ",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/o8.jpg?alt=media&token=6ebf2886-b8d8-4aa4-8f0a-a6dffb779b5e",
    description: "Gạo ngon nhất thế giới",
    categoryId: "wVaMcDH4yni65ls9aY3C",
    discount: 10,
    price: 81000,
    quantity: 100,
    unit: "kg",
    rating: 2,
    createdDate: {
      seconds: 1627273448,
      nanoseconds: 878000000,
    },
  },
  {
    id: "I7HN5f55vDXKU3rFdYwB",
    discount: 51,
    productName: "Đậu le men",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s13.jpg?alt=media&token=88977ddb-a119-46ed-8963-5846cfab92de",
    keywords: [
      "d",
      "da",
      "dau",
      "dau ",
      "dau l",
      "dau le",
      "dau le ",
      "dau le m",
      "dau le me",
      "dau le men",
      "d",
      "da",
      "dau",
      "dau ",
      "dau m",
      "dau me",
      "dau men",
      "dau men ",
      "dau men l",
      "dau men le",
      "l",
      "le",
      "le ",
      "le d",
      "le da",
      "le dau",
      "le dau ",
      "le dau m",
      "le dau me",
      "le dau men",
      "l",
      "le",
      "le ",
      "le m",
      "le me",
      "le men",
      "le men ",
      "le men d",
      "le men da",
      "le men dau",
      "m",
      "me",
      "men",
      "men ",
      "men d",
      "men da",
      "men dau",
      "men dau ",
      "men dau l",
      "men dau le",
      "m",
      "me",
      "men",
      "men ",
      "men l",
      "men le",
      "men le ",
      "men le d",
      "men le da",
      "men le dau",
    ],
    description: "Đậu hà lan ngâm nước",
    categoryId: "D12YC358aOe71ZVhrdOf",
    rating: 3,
    quantity: 31,
    price: 34000,
    createdDate: {
      seconds: 1627273330,
      nanoseconds: 40000000,
    },
    unit: "Sản phẩm",
  },
  {
    id: "uazkwG7rxAXpUZ6YZls8",
    discount: 70,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s8.jpg?alt=media&token=9724b958-b5f4-4221-a871-6b35f3023dc0",
    categoryId: "D12YC358aOe71ZVhrdOf",
    price: 210000,
    description: "Hàng nhập khẩu",
    unit: "Sản phẩm",
    productName: "Sốt mận",
    keywords: [
      "s",
      "so",
      "sot",
      "sot ",
      "sot m",
      "sot ma",
      "sot man",
      "m",
      "ma",
      "man",
      "man ",
      "man s",
      "man so",
      "man sot",
    ],
    createdDate: {
      seconds: 1627273200,
      nanoseconds: 44000000,
    },
    rating: 3,
    quantity: 21,
  },
  {
    id: "JOnoPXQgXHLjwEpyAg1G",
    quantity: 21,
    price: 170000,
    unit: "Quả",
    discount: 77,
    categoryId: "X63OeZXLKAqyVcAm38aT",
    productName: "Trái bơ Thái Lan",
    rating: 3,
    createdDate: {
      seconds: 1627273127,
      nanoseconds: 406000000,
    },
    description: "Trồng tại Thái Lan",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/fr13.jpg?alt=media&token=9cf9f46e-18bd-4e4f-80b3-be8d396860b1",
    keywords: [
      "t",
      "tr",
      "tra",
      "trai",
      "trai ",
      "trai b",
      "trai bo",
      "trai bo ",
      "trai bo t",
      "trai bo th",
      "trai bo tha",
      "trai bo thai",
      "trai bo thai ",
      "trai bo thai l",
      "trai bo thai la",
      "trai bo thai lan",
      "t",
      "tr",
      "tra",
      "trai",
      "trai ",
      "trai b",
      "trai bo",
      "trai bo ",
      "trai bo l",
      "trai bo la",
      "trai bo lan",
      "trai bo lan ",
      "trai bo lan t",
      "trai bo lan th",
      "trai bo lan tha",
      "trai bo lan thai",
      "t",
      "tr",
      "tra",
      "trai",
      "trai ",
      "trai t",
      "trai th",
      "trai tha",
      "trai thai",
      "trai thai ",
      "trai thai b",
      "trai thai bo",
      "trai thai bo ",
      "trai thai bo l",
      "trai thai bo la",
      "trai thai bo lan",
      "t",
      "tr",
      "tra",
      "trai",
      "trai ",
      "trai t",
      "trai th",
      "trai tha",
      "trai thai",
      "trai thai ",
      "trai thai l",
      "trai thai la",
      "trai thai lan",
      "trai thai lan ",
      "trai thai lan b",
      "trai thai lan bo",
      "t",
      "tr",
      "tra",
      "trai",
      "trai ",
      "trai l",
      "trai la",
      "trai lan",
      "trai lan ",
      "trai lan b",
      "trai lan bo",
      "trai lan bo ",
      "trai lan bo t",
      "trai lan bo th",
      "trai lan bo tha",
      "trai lan bo thai",
      "t",
      "tr",
      "tra",
      "trai",
      "trai ",
      "trai l",
      "trai la",
      "trai lan",
      "trai lan ",
      "trai lan t",
      "trai lan th",
      "trai lan tha",
      "trai lan thai",
      "trai lan thai ",
      "trai lan thai b",
      "trai lan thai bo",
      "b",
      "bo",
      "bo ",
      "bo t",
      "bo tr",
      "bo tra",
      "bo trai",
      "bo trai ",
      "bo trai t",
      "bo trai th",
      "bo trai tha",
      "bo trai thai",
      "bo trai thai ",
      "bo trai thai l",
      "bo trai thai la",
      "bo trai thai lan",
      "b",
      "bo",
      "bo ",
      "bo t",
      "bo tr",
      "bo tra",
      "bo trai",
      "bo trai ",
      "bo trai l",
      "bo trai la",
      "bo trai lan",
      "bo trai lan ",
      "bo trai lan t",
      "bo trai lan th",
      "bo trai lan tha",
      "bo trai lan thai",
      "b",
      "bo",
      "bo ",
      "bo t",
      "bo th",
      "bo tha",
      "bo thai",
      "bo thai ",
      "bo thai t",
      "bo thai tr",
      "bo thai tra",
      "bo thai trai",
      "bo thai trai ",
      "bo thai trai l",
      "bo thai trai la",
      "bo thai trai lan",
      "b",
      "bo",
      "bo ",
      "bo t",
      "bo th",
      "bo tha",
      "bo thai",
      "bo thai ",
      "bo thai l",
      "bo thai la",
      "bo thai lan",
      "bo thai lan ",
      "bo thai lan t",
      "bo thai lan tr",
      "bo thai lan tra",
      "bo thai lan trai",
      "b",
      "bo",
      "bo ",
      "bo l",
      "bo la",
      "bo lan",
      "bo lan ",
      "bo lan t",
      "bo lan tr",
      "bo lan tra",
      "bo lan trai",
      "bo lan trai ",
      "bo lan trai t",
      "bo lan trai th",
      "bo lan trai tha",
      "bo lan trai thai",
      "b",
      "bo",
      "bo ",
      "bo l",
      "bo la",
      "bo lan",
      "bo lan ",
      "bo lan t",
      "bo lan th",
      "bo lan tha",
      "bo lan thai",
      "bo lan thai ",
      "bo lan thai t",
      "bo lan thai tr",
      "bo lan thai tra",
      "bo lan thai trai",
      "t",
      "th",
      "tha",
      "thai",
      "thai ",
      "thai t",
      "thai tr",
      "thai tra",
      "thai trai",
      "thai trai ",
      "thai trai b",
      "thai trai bo",
      "thai trai bo ",
      "thai trai bo l",
      "thai trai bo la",
      "thai trai bo lan",
      "t",
      "th",
      "tha",
      "thai",
      "thai ",
      "thai t",
      "thai tr",
      "thai tra",
      "thai trai",
      "thai trai ",
      "thai trai l",
      "thai trai la",
      "thai trai lan",
      "thai trai lan ",
      "thai trai lan b",
      "thai trai lan bo",
      "t",
      "th",
      "tha",
      "thai",
      "thai ",
      "thai b",
      "thai bo",
      "thai bo ",
      "thai bo t",
      "thai bo tr",
      "thai bo tra",
      "thai bo trai",
      "thai bo trai ",
      "thai bo trai l",
      "thai bo trai la",
      "thai bo trai lan",
      "t",
      "th",
      "tha",
      "thai",
      "thai ",
      "thai b",
      "thai bo",
      "thai bo ",
      "thai bo l",
      "thai bo la",
      "thai bo lan",
      "thai bo lan ",
      "thai bo lan t",
      "thai bo lan tr",
      "thai bo lan tra",
      "thai bo lan trai",
      "t",
      "th",
      "tha",
      "thai",
      "thai ",
      "thai l",
      "thai la",
      "thai lan",
      "thai lan ",
      "thai lan t",
      "thai lan tr",
      "thai lan tra",
      "thai lan trai",
      "thai lan trai ",
      "thai lan trai b",
      "thai lan trai bo",
      "t",
      "th",
      "tha",
      "thai",
      "thai ",
      "thai l",
      "thai la",
      "thai lan",
      "thai lan ",
      "thai lan b",
      "thai lan bo",
      "thai lan bo ",
      "thai lan bo t",
      "thai lan bo tr",
      "thai lan bo tra",
      "thai lan bo trai",
      "l",
      "la",
      "lan",
      "lan ",
      "lan t",
      "lan tr",
      "lan tra",
      "lan trai",
      "lan trai ",
      "lan trai b",
      "lan trai bo",
      "lan trai bo ",
      "lan trai bo t",
      "lan trai bo th",
      "lan trai bo tha",
      "lan trai bo thai",
      "l",
      "la",
      "lan",
      "lan ",
      "lan t",
      "lan tr",
      "lan tra",
      "lan trai",
      "lan trai ",
      "lan trai t",
      "lan trai th",
      "lan trai tha",
      "lan trai thai",
      "lan trai thai ",
      "lan trai thai b",
      "lan trai thai bo",
      "l",
      "la",
      "lan",
      "lan ",
      "lan b",
      "lan bo",
      "lan bo ",
      "lan bo t",
      "lan bo tr",
      "lan bo tra",
      "lan bo trai",
      "lan bo trai ",
      "lan bo trai t",
      "lan bo trai th",
      "lan bo trai tha",
      "lan bo trai thai",
      "l",
      "la",
      "lan",
      "lan ",
      "lan b",
      "lan bo",
      "lan bo ",
      "lan bo t",
      "lan bo th",
      "lan bo tha",
      "lan bo thai",
      "lan bo thai ",
      "lan bo thai t",
      "lan bo thai tr",
      "lan bo thai tra",
      "lan bo thai trai",
      "l",
      "la",
      "lan",
      "lan ",
      "lan t",
      "lan th",
      "lan tha",
      "lan thai",
      "lan thai ",
      "lan thai t",
      "lan thai tr",
      "lan thai tra",
      "lan thai trai",
      "lan thai trai ",
      "lan thai trai b",
      "lan thai trai bo",
      "l",
      "la",
      "lan",
      "lan ",
      "lan t",
      "lan th",
      "lan tha",
      "lan thai",
      "lan thai ",
      "lan thai b",
      "lan thai bo",
      "lan thai bo ",
      "lan thai bo t",
      "lan thai bo tr",
      "lan thai bo tra",
      "lan thai bo trai",
    ],
  },
  {
    id: "cDKPInqeiYaMEncU0a5J",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v2.jpg?alt=media&token=364878cd-9632-45ce-aded-5b1cf5799488",
    keywords: [
      "b",
      "ba",
      "bap",
      "bap ",
      "bap c",
      "bap ca",
      "bap cai",
      "c",
      "ca",
      "cai",
      "cai ",
      "cai b",
      "cai ba",
      "cai bap",
    ],
    quantity: 61,
    discount: 31,
    price: 71000,
    rating: 2,
    description: "Không hóa chất",
    createdDate: {
      seconds: 1627273030,
      nanoseconds: 319000000,
    },
    unit: "kg",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    productName: "Bắp cải",
  },
  {
    id: "mxLmlV8C60WMpIiMh1IG",
    quantity: 100,
    description: "Vị táo, dâu, chanh",
    discount: 1,
    createdDate: {
      seconds: 1627266092,
      nanoseconds: 34000000,
    },
    categoryId: "WLCBEkRzCY5H703DUO4o",
    rating: 2,
    keywords: [
      "n",
      "nu",
      "nuo",
      "nuoc",
      "nuoc ",
      "nuoc h",
      "nuoc ho",
      "nuoc hoa",
      "nuoc hoa ",
      "nuoc hoa q",
      "nuoc hoa qu",
      "nuoc hoa qua",
      "n",
      "nu",
      "nuo",
      "nuoc",
      "nuoc ",
      "nuoc q",
      "nuoc qu",
      "nuoc qua",
      "nuoc qua ",
      "nuoc qua h",
      "nuoc qua ho",
      "nuoc qua hoa",
      "h",
      "ho",
      "hoa",
      "hoa ",
      "hoa n",
      "hoa nu",
      "hoa nuo",
      "hoa nuoc",
      "hoa nuoc ",
      "hoa nuoc q",
      "hoa nuoc qu",
      "hoa nuoc qua",
      "h",
      "ho",
      "hoa",
      "hoa ",
      "hoa q",
      "hoa qu",
      "hoa qua",
      "hoa qua ",
      "hoa qua n",
      "hoa qua nu",
      "hoa qua nuo",
      "hoa qua nuoc",
      "q",
      "qu",
      "qua",
      "qua ",
      "qua n",
      "qua nu",
      "qua nuo",
      "qua nuoc",
      "qua nuoc ",
      "qua nuoc h",
      "qua nuoc ho",
      "qua nuoc hoa",
      "q",
      "qu",
      "qua",
      "qua ",
      "qua h",
      "qua ho",
      "qua hoa",
      "qua hoa ",
      "qua hoa n",
      "qua hoa nu",
      "qua hoa nuo",
      "qua hoa nuoc",
    ],
    productName: "Nước hoa quả",
    unit: "Sản phẩm",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s4.jpg?alt=media&token=462390b6-803f-4d0d-ae77-c4527a71a642",
    price: 3000,
  },
  {
    id: "dg3hbnLaifrecpzS2FC3",
    unit: "Sản phẩm",
    productName: "Sốt táo",
    description: "Sốt hoa quả",
    categoryId: "D12YC358aOe71ZVhrdOf",
    createdDate: {
      seconds: 1627266024,
      nanoseconds: 246000000,
    },
    rating: 2,
    price: 14000,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s10.jpg?alt=media&token=ce81ae5b-10ad-439d-ac3b-f03dd7acfaae",
    quantity: 10,
    keywords: [
      "s",
      "so",
      "sot",
      "sot ",
      "sot t",
      "sot ta",
      "sot tao",
      "t",
      "ta",
      "tao",
      "tao ",
      "tao s",
      "tao so",
      "tao sot",
    ],
    discount: 7,
  },
  {
    id: "5ENCo4GyLXuUrWg8ZtmT",
    discount: 60,
    rating: 2,
    price: 66000,
    unit: "Quả",
    keywords: [
      "q",
      "qu",
      "qua",
      "qua ",
      "qua l",
      "qua lu",
      "qua luu",
      "l",
      "lu",
      "luu",
      "luu ",
      "luu q",
      "luu qu",
      "luu qua",
    ],
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/fr5.jpg?alt=media&token=62ff3efc-4812-4956-a5a4-e40c9dc4e8f8",
    quantity: 41,
    productName: "Quả Lựu",
    description: "Ngon, ngọt lịm",
    createdDate: {
      seconds: 1627265824,
      nanoseconds: 958000000,
    },
    categoryId: "X63OeZXLKAqyVcAm38aT",
  },
  {
    id: "rgNRCC7TQ1HWM8DFDRMK",
    productName: "Ớt chuông",
    price: 190000,
    keywords: [
      "o",
      "ot",
      "ot ",
      "ot c",
      "ot ch",
      "ot chu",
      "ot chuo",
      "ot chuon",
      "ot chuong",
      "c",
      "ch",
      "chu",
      "chuo",
      "chuon",
      "chuong",
      "chuong ",
      "chuong o",
      "chuong ot",
    ],
    createdDate: {
      seconds: 1627265749,
      nanoseconds: 92000000,
    },
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v20.jpg?alt=media&token=46711d02-525d-4929-b193-b1a315e7d3f5",
    description: "Vị cay ngọt",
    unit: "g",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    quantity: 100,
    discount: 15,
    rating: 4,
  },
  {
    id: "eqXrMkJzmmZeW9h1MWxI",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    rating: 4,
    price: 31000,
    productName: "Nấm hương",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v12.jpg?alt=media&token=87a8de1e-b90e-4fa9-ab55-c213db9e968c",
    discount: 21,
    quantity: 16,
    keywords: [
      "n",
      "na",
      "nam",
      "nam ",
      "nam h",
      "nam hu",
      "nam huo",
      "nam huon",
      "nam huong",
      "h",
      "hu",
      "huo",
      "huon",
      "huong",
      "huong ",
      "huong n",
      "huong na",
      "huong nam",
    ],
    unit: "kg",
    createdDate: {
      seconds: 1627265702,
      nanoseconds: 208000000,
    },
    description: "Nuôi trồng trong lồng kính",
  },
  {
    id: "2bd6excCHmpLRSHqmxRd",
    createdDate: {
      seconds: 1627265618,
      nanoseconds: 168000000,
    },
    keywords: [
      "s",
      "si",
      "sin",
      "sinh",
      "sinh ",
      "sinh t",
      "sinh to",
      "sinh to ",
      "sinh to k",
      "sinh to ki",
      "sinh to kiw",
      "sinh to kiwi",
      "s",
      "si",
      "sin",
      "sinh",
      "sinh ",
      "sinh k",
      "sinh ki",
      "sinh kiw",
      "sinh kiwi",
      "sinh kiwi ",
      "sinh kiwi t",
      "sinh kiwi to",
      "t",
      "to",
      "to ",
      "to s",
      "to si",
      "to sin",
      "to sinh",
      "to sinh ",
      "to sinh k",
      "to sinh ki",
      "to sinh kiw",
      "to sinh kiwi",
      "t",
      "to",
      "to ",
      "to k",
      "to ki",
      "to kiw",
      "to kiwi",
      "to kiwi ",
      "to kiwi s",
      "to kiwi si",
      "to kiwi sin",
      "to kiwi sinh",
      "k",
      "ki",
      "kiw",
      "kiwi",
      "kiwi ",
      "kiwi s",
      "kiwi si",
      "kiwi sin",
      "kiwi sinh",
      "kiwi sinh ",
      "kiwi sinh t",
      "kiwi sinh to",
      "k",
      "ki",
      "kiw",
      "kiwi",
      "kiwi ",
      "kiwi t",
      "kiwi to",
      "kiwi to ",
      "kiwi to s",
      "kiwi to si",
      "kiwi to sin",
      "kiwi to sinh",
    ],
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s3.jpg?alt=media&token=3483fea3-a221-4a2b-95c9-05e153015181",
    unit: "Sản phẩm",
    rating: 3,
    discount: 51,
    productName: "Sinh tố Kiwi",
    price: 77000,
    categoryId: "WLCBEkRzCY5H703DUO4o",
    quantity: 30,
    description: "Chứa Kiwi tự nhiên tốt cho sức khỏe",
  },
  {
    id: "JVnX9MwWQXfGLOBYJJoq",
    createdDate: {
      seconds: 1627265566,
      nanoseconds: 9000000,
    },
    rating: 4,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/b9.jpg?alt=media&token=8818ef91-b7cf-4a16-9c5f-49ceb9c817a4",
    discount: 19,
    categoryId: "ucZK9up2unneAdUkXNRn",
    quantity: 77,
    description: "Pizza chesse hải sản full topping",
    productName: "Pizza",
    price: 120000,
    unit: "Sản phẩm",
    keywords: ["p", "pi", "piz", "pizz", "pizza"],
  },
  {
    id: "tSzyvsFWPpGOCDMV6F5F",
    description: "Sản xuất và chế biến tại Thụy Sĩ",
    keywords: [
      "p",
      "ph",
      "pho",
      "pho ",
      "pho m",
      "pho ma",
      "pho mat",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat p",
      "mat ph",
      "mat pho",
    ],
    quantity: 10,
    discount: 21,
    unit: "Sản phẩm",
    rating: 3,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/o2.jpg?alt=media&token=ac58cd72-cd42-4171-b827-9c841135be6b",
    productName: "Pho mát",
    updatedDate: {
      seconds: 1626977689,
      nanoseconds: 906000000,
    },
    createdDate: {
      seconds: 1626905609,
      nanoseconds: 8000000,
    },
    categoryId: "wVaMcDH4yni65ls9aY3C",
    price: 200000,
  },
  {
    id: "4JXARFWkVXn7sG4oRIia",
    comments: [
      {
        user: {
          id: "WhLJr4zSoxQbOXvueApCGuWYBB22",
          avatar:
            "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/avatarr_photos_v2_faces_x2.jpg?alt=media&token=35b8627e-f79b-4070-88ff-476ab0e8903e",
          name: "Nguyễn Văn Khánh",
        },
        rating: 4,
        comment: "hay qua cac ban oi",
      },
    ],
    keywords: [
      "t",
      "th",
      "thi",
      "thit",
      "thit ",
      "thit g",
      "thit ga",
      "g",
      "ga",
      "ga ",
      "ga t",
      "ga th",
      "ga thi",
      "ga thit",
    ],
    createdDate: {
      seconds: 1626905355,
      nanoseconds: 932000000,
    },
    productName: "Thịt gà",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/meat1.jpg?alt=media&token=08e18f3e-607c-4999-a1a5-ea71a46087ab",
    price: 32000,
    quantity: 98,
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    rating: 4,
    unit: "kg",
    description: "Gà ta",
    comment: [""],
    updatedDate: {
      seconds: 1626977816,
      nanoseconds: 225000000,
    },
    discount: 12,
  },
  {
    id: "4TIh5zoOHZ6mJtraFX0g",
    rating: 3,
    createdDate: {
      seconds: 1626905206,
      nanoseconds: 679000000,
    },
    quantity: 26,
    description: "Siêu chua",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/fr7.jpg?alt=media&token=6261356d-58ab-40ee-90ad-9797d3b4c3ef",
    unit: "kg",
    productName: "Chanh leo",
    updatedDate: {
      seconds: 1626977697,
      nanoseconds: 319000000,
    },
    price: 17000,
    categoryId: "X63OeZXLKAqyVcAm38aT",
    keywords: [
      "c",
      "ch",
      "cha",
      "chan",
      "chanh",
      "chanh ",
      "chanh l",
      "chanh le",
      "chanh leo",
      "l",
      "le",
      "leo",
      "leo ",
      "leo c",
      "leo ch",
      "leo cha",
      "leo chan",
      "leo chanh",
    ],
    discount: 15,
  },
  {
    id: "LwdcfSlcruJIkVfPbENC",
    updatedDate: {
      seconds: 1626977819,
      nanoseconds: 931000000,
    },
    unit: "kg",
    description: "Đỏ chín",
    createdDate: {
      seconds: 1626905141,
      nanoseconds: 131000000,
    },
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    rating: 2,
    discount: 21,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v8.jpg?alt=media&token=650c09e1-6c68-4b0b-a76b-b9f1e5601f11",
    quantity: 100,
    keywords: [
      "c",
      "ca",
      "ca ",
      "ca c",
      "ca ch",
      "ca chu",
      "ca chua",
      "c",
      "ch",
      "chu",
      "chua",
      "chua ",
      "chua c",
      "chua ca",
    ],
    productName: "Cà chua",
    price: 23000,
  },
  {
    id: "Ctfx7SwTyjtRLoVBxOrG",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    rating: 2,
    keywords: ["n", "ng", "ngo"],
    price: 16000,
    updatedDate: {
      seconds: 1626977722,
      nanoseconds: 79000000,
    },
    discount: 27,
    productName: "Ngô",
    quantity: 100,
    description: "Ngô ngọt",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v17.jpg?alt=media&token=5bea7ae9-d1cf-4afe-b37d-93e6e4b3966a",
    unit: "kg",
    createdDate: {
      seconds: 1626905070,
      nanoseconds: 175000000,
    },
  },
  {
    id: "ccyoMLSSElZxU2AcJxzT",
    categoryId: "WLCBEkRzCY5H703DUO4o",
    updatedDate: {
      seconds: 1626977726,
      nanoseconds: 807000000,
    },
    price: 15000,
    productName: "Nước ép cà rốt",
    createdDate: {
      seconds: 1626905012,
      nanoseconds: 523000000,
    },
    unit: "Sản phẩm",
    discount: 9,
    rating: 2,
    description: "Nguyên chất",
    quantity: 31,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s2.jpg?alt=media&token=03f7dd9f-ef18-4741-b870-90ce393c6be0",
    keywords: [
      "n",
      "nu",
      "nuo",
      "nuoc",
      "nuoc ",
      "nuoc e",
      "nuoc ep",
      "nuoc ep ",
      "nuoc ep c",
      "nuoc ep ca",
      "nuoc ep ca ",
      "nuoc ep ca r",
      "nuoc ep ca ro",
      "nuoc ep ca rot",
      "n",
      "nu",
      "nuo",
      "nuoc",
      "nuoc ",
      "nuoc e",
      "nuoc ep",
      "nuoc ep ",
      "nuoc ep r",
      "nuoc ep ro",
      "nuoc ep rot",
      "nuoc ep rot ",
      "nuoc ep rot c",
      "nuoc ep rot ca",
      "n",
      "nu",
      "nuo",
      "nuoc",
      "nuoc ",
      "nuoc c",
      "nuoc ca",
      "nuoc ca ",
      "nuoc ca e",
      "nuoc ca ep",
      "nuoc ca ep ",
      "nuoc ca ep r",
      "nuoc ca ep ro",
      "nuoc ca ep rot",
      "n",
      "nu",
      "nuo",
      "nuoc",
      "nuoc ",
      "nuoc c",
      "nuoc ca",
      "nuoc ca ",
      "nuoc ca r",
      "nuoc ca ro",
      "nuoc ca rot",
      "nuoc ca rot ",
      "nuoc ca rot e",
      "nuoc ca rot ep",
      "n",
      "nu",
      "nuo",
      "nuoc",
      "nuoc ",
      "nuoc r",
      "nuoc ro",
      "nuoc rot",
      "nuoc rot ",
      "nuoc rot e",
      "nuoc rot ep",
      "nuoc rot ep ",
      "nuoc rot ep c",
      "nuoc rot ep ca",
      "n",
      "nu",
      "nuo",
      "nuoc",
      "nuoc ",
      "nuoc r",
      "nuoc ro",
      "nuoc rot",
      "nuoc rot ",
      "nuoc rot c",
      "nuoc rot ca",
      "nuoc rot ca ",
      "nuoc rot ca e",
      "nuoc rot ca ep",
      "e",
      "ep",
      "ep ",
      "ep n",
      "ep nu",
      "ep nuo",
      "ep nuoc",
      "ep nuoc ",
      "ep nuoc c",
      "ep nuoc ca",
      "ep nuoc ca ",
      "ep nuoc ca r",
      "ep nuoc ca ro",
      "ep nuoc ca rot",
      "e",
      "ep",
      "ep ",
      "ep n",
      "ep nu",
      "ep nuo",
      "ep nuoc",
      "ep nuoc ",
      "ep nuoc r",
      "ep nuoc ro",
      "ep nuoc rot",
      "ep nuoc rot ",
      "ep nuoc rot c",
      "ep nuoc rot ca",
      "e",
      "ep",
      "ep ",
      "ep c",
      "ep ca",
      "ep ca ",
      "ep ca n",
      "ep ca nu",
      "ep ca nuo",
      "ep ca nuoc",
      "ep ca nuoc ",
      "ep ca nuoc r",
      "ep ca nuoc ro",
      "ep ca nuoc rot",
      "e",
      "ep",
      "ep ",
      "ep c",
      "ep ca",
      "ep ca ",
      "ep ca r",
      "ep ca ro",
      "ep ca rot",
      "ep ca rot ",
      "ep ca rot n",
      "ep ca rot nu",
      "ep ca rot nuo",
      "ep ca rot nuoc",
      "e",
      "ep",
      "ep ",
      "ep r",
      "ep ro",
      "ep rot",
      "ep rot ",
      "ep rot n",
      "ep rot nu",
      "ep rot nuo",
      "ep rot nuoc",
      "ep rot nuoc ",
      "ep rot nuoc c",
      "ep rot nuoc ca",
      "e",
      "ep",
      "ep ",
      "ep r",
      "ep ro",
      "ep rot",
      "ep rot ",
      "ep rot c",
      "ep rot ca",
      "ep rot ca ",
      "ep rot ca n",
      "ep rot ca nu",
      "ep rot ca nuo",
      "ep rot ca nuoc",
      "c",
      "ca",
      "ca ",
      "ca n",
      "ca nu",
      "ca nuo",
      "ca nuoc",
      "ca nuoc ",
      "ca nuoc e",
      "ca nuoc ep",
      "ca nuoc ep ",
      "ca nuoc ep r",
      "ca nuoc ep ro",
      "ca nuoc ep rot",
      "c",
      "ca",
      "ca ",
      "ca n",
      "ca nu",
      "ca nuo",
      "ca nuoc",
      "ca nuoc ",
      "ca nuoc r",
      "ca nuoc ro",
      "ca nuoc rot",
      "ca nuoc rot ",
      "ca nuoc rot e",
      "ca nuoc rot ep",
      "c",
      "ca",
      "ca ",
      "ca e",
      "ca ep",
      "ca ep ",
      "ca ep n",
      "ca ep nu",
      "ca ep nuo",
      "ca ep nuoc",
      "ca ep nuoc ",
      "ca ep nuoc r",
      "ca ep nuoc ro",
      "ca ep nuoc rot",
      "c",
      "ca",
      "ca ",
      "ca e",
      "ca ep",
      "ca ep ",
      "ca ep r",
      "ca ep ro",
      "ca ep rot",
      "ca ep rot ",
      "ca ep rot n",
      "ca ep rot nu",
      "ca ep rot nuo",
      "ca ep rot nuoc",
      "c",
      "ca",
      "ca ",
      "ca r",
      "ca ro",
      "ca rot",
      "ca rot ",
      "ca rot n",
      "ca rot nu",
      "ca rot nuo",
      "ca rot nuoc",
      "ca rot nuoc ",
      "ca rot nuoc e",
      "ca rot nuoc ep",
      "c",
      "ca",
      "ca ",
      "ca r",
      "ca ro",
      "ca rot",
      "ca rot ",
      "ca rot e",
      "ca rot ep",
      "ca rot ep ",
      "ca rot ep n",
      "ca rot ep nu",
      "ca rot ep nuo",
      "ca rot ep nuoc",
      "r",
      "ro",
      "rot",
      "rot ",
      "rot n",
      "rot nu",
      "rot nuo",
      "rot nuoc",
      "rot nuoc ",
      "rot nuoc e",
      "rot nuoc ep",
      "rot nuoc ep ",
      "rot nuoc ep c",
      "rot nuoc ep ca",
      "r",
      "ro",
      "rot",
      "rot ",
      "rot n",
      "rot nu",
      "rot nuo",
      "rot nuoc",
      "rot nuoc ",
      "rot nuoc c",
      "rot nuoc ca",
      "rot nuoc ca ",
      "rot nuoc ca e",
      "rot nuoc ca ep",
      "r",
      "ro",
      "rot",
      "rot ",
      "rot e",
      "rot ep",
      "rot ep ",
      "rot ep n",
      "rot ep nu",
      "rot ep nuo",
      "rot ep nuoc",
      "rot ep nuoc ",
      "rot ep nuoc c",
      "rot ep nuoc ca",
      "r",
      "ro",
      "rot",
      "rot ",
      "rot e",
      "rot ep",
      "rot ep ",
      "rot ep c",
      "rot ep ca",
      "rot ep ca ",
      "rot ep ca n",
      "rot ep ca nu",
      "rot ep ca nuo",
      "rot ep ca nuoc",
      "r",
      "ro",
      "rot",
      "rot ",
      "rot c",
      "rot ca",
      "rot ca ",
      "rot ca n",
      "rot ca nu",
      "rot ca nuo",
      "rot ca nuoc",
      "rot ca nuoc ",
      "rot ca nuoc e",
      "rot ca nuoc ep",
      "r",
      "ro",
      "rot",
      "rot ",
      "rot c",
      "rot ca",
      "rot ca ",
      "rot ca e",
      "rot ca ep",
      "rot ca ep ",
      "rot ca ep n",
      "rot ca ep nu",
      "rot ca ep nuo",
      "rot ca ep nuoc",
    ],
  },
  {
    id: "t3uPLMSBLKBxd3AbxpFE",
    createdDate: {
      seconds: 1626904842,
      nanoseconds: 93000000,
    },
    updatedDate: {
      seconds: 1626977731,
      nanoseconds: 679000000,
    },
    unit: "kg",
    discount: 15,
    price: 40000,
    keywords: [
      "g",
      "ga",
      "gao",
      "gao ",
      "gao l",
      "gao lu",
      "gao lut",
      "l",
      "lu",
      "lut",
      "lut ",
      "lut g",
      "lut ga",
      "lut gao",
    ],
    description: "Hảo hạng",
    rating: 2,
    categoryId: "wVaMcDH4yni65ls9aY3C",
    quantity: 100,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/o5.jpg?alt=media&token=0bd19a12-ede3-424f-bf8f-fc1272218b3e",
    productName: "Gạo lứt",
  },
  {
    id: "TOP5HloARKzbMvLTxXkw",
    createdDate: {
      seconds: 1626904782,
      nanoseconds: 734000000,
    },
    unit: "Sản phẩm",
    price: 60000,
    productName: "Hoa chuối",
    rating: 3,
    keywords: [
      "h",
      "ho",
      "hoa",
      "hoa ",
      "hoa c",
      "hoa ch",
      "hoa chu",
      "hoa chuo",
      "hoa chuoi",
      "c",
      "ch",
      "chu",
      "chuo",
      "chuoi",
      "chuoi ",
      "chuoi h",
      "chuoi ho",
      "chuoi hoa",
    ],
    updatedDate: {
      seconds: 1626977737,
      nanoseconds: 162000000,
    },
    discount: 15,
    description: "Nhập khẩu Thái Lan",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s6.jpg?alt=media&token=17a9bb35-1cb1-49b1-9fbc-7f9ba2645a5e",
    quantity: 31,
    categoryId: "D12YC358aOe71ZVhrdOf",
  },
  {
    id: "69vq0fbB5MqxRsKXJSoV",
    description: "Nhập khẩu",
    productName: "Táo Nhật Bản",
    unit: "g",
    quantity: 10,
    discount: 20,
    rating: 3,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/fr3.jpg?alt=media&token=d7257824-da39-4853-abea-c7c2646fa8c8",
    keywords: [
      "t",
      "ta",
      "tao",
      "tao ",
      "tao n",
      "tao nh",
      "tao nha",
      "tao nhat",
      "tao nhat ",
      "tao nhat b",
      "tao nhat ba",
      "tao nhat ban",
      "t",
      "ta",
      "tao",
      "tao ",
      "tao b",
      "tao ba",
      "tao ban",
      "tao ban ",
      "tao ban n",
      "tao ban nh",
      "tao ban nha",
      "tao ban nhat",
      "n",
      "nh",
      "nha",
      "nhat",
      "nhat ",
      "nhat t",
      "nhat ta",
      "nhat tao",
      "nhat tao ",
      "nhat tao b",
      "nhat tao ba",
      "nhat tao ban",
      "n",
      "nh",
      "nha",
      "nhat",
      "nhat ",
      "nhat b",
      "nhat ba",
      "nhat ban",
      "nhat ban ",
      "nhat ban t",
      "nhat ban ta",
      "nhat ban tao",
      "b",
      "ba",
      "ban",
      "ban ",
      "ban t",
      "ban ta",
      "ban tao",
      "ban tao ",
      "ban tao n",
      "ban tao nh",
      "ban tao nha",
      "ban tao nhat",
      "b",
      "ba",
      "ban",
      "ban ",
      "ban n",
      "ban nh",
      "ban nha",
      "ban nhat",
      "ban nhat ",
      "ban nhat t",
      "ban nhat ta",
      "ban nhat tao",
    ],
    price: 34000,
    updatedDate: {
      seconds: 1626977742,
      nanoseconds: 964000000,
    },
    createdDate: {
      seconds: 1626904618,
      nanoseconds: 530000000,
    },
    categoryId: "X63OeZXLKAqyVcAm38aT",
  },
  {
    id: "uUzU3IUn25FRaKeoXTXy",
    productName: "Trứng gà",
    createdDate: {
      seconds: 1626904566,
      nanoseconds: 279000000,
    },
    categoryId: "wVaMcDH4yni65ls9aY3C",
    keywords: [
      "t",
      "tr",
      "tru",
      "trun",
      "trung",
      "trung ",
      "trung g",
      "trung ga",
      "g",
      "ga",
      "ga ",
      "ga t",
      "ga tr",
      "ga tru",
      "ga trun",
      "ga trung",
    ],
    price: 3000,
    description: "Trứng gà ta",
    quantity: 100,
    rating: 2,
    updatedDate: {
      seconds: 1626999373,
      nanoseconds: 898000000,
    },
    unit: "Quả",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/o1.jpg?alt=media&token=c316fd4d-8c27-448e-b951-17353630bb25",
    discount: 10,
  },
  {
    id: "5DvQPYQPm7qoEmuEos1P",
    price: 7000,
    quantity: 21,
    keywords: [
      "n",
      "nu",
      "nuo",
      "nuoc",
      "nuoc ",
      "nuoc c",
      "nuoc ca",
      "nuoc cam",
      "c",
      "ca",
      "cam",
      "cam ",
      "cam n",
      "cam nu",
      "cam nuo",
      "cam nuoc",
    ],
    unit: "Sản phẩm",
    createdDate: {
      seconds: 1626904504,
      nanoseconds: 795000000,
    },
    updatedDate: {
      seconds: 1627277931,
      nanoseconds: 83000000,
    },
    categoryId: "WLCBEkRzCY5H703DUO4o",
    discount: 5,
    rating: 2,
    productName: "Nước cam",
    description: "Cam nguyên chất",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/s1.jpg?alt=media&token=99693209-6bf3-4379-864d-8c126826e3db",
  },
  {
    id: "lMAgGaOwGEM9vDkiQwru",
    quantity: 10,
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/meat2.jpg?alt=media&token=8f487361-e59e-41ed-950f-4823263949d4",
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    rating: 5,
    productName: "Thăn bò",
    discount: 15,
    price: 30000,
    unit: "g",
    description: "Bò Mỹ hảo hạng",
    updatedDate: {
      seconds: 1626975531,
      nanoseconds: 854000000,
    },
    createdDate: {
      seconds: 1626904368,
      nanoseconds: 521000000,
    },
    keywords: [
      "t",
      "th",
      "tha",
      "than",
      "than ",
      "than b",
      "than bo",
      "b",
      "bo",
      "bo ",
      "bo t",
      "bo th",
      "bo tha",
      "bo than",
    ],
  },
  {
    id: "DkPxJCCMchj0fLbjd9kL",
    description: "Mật ong tự nhiên",
    discount: 10,
    categoryId: "ucZK9up2unneAdUkXNRn",
    updatedDate: {
      seconds: 1626977785,
      nanoseconds: 417000000,
    },
    quantity: 10,
    rating: 4,
    productName: "Bánh mì mật ong",
    price: 17000,
    createdDate: {
      seconds: 1626904306,
      nanoseconds: 407000000,
    },
    unit: "Sản phẩm",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/b3.jpg?alt=media&token=d496d227-d08a-42f0-9578-ab616cdc4cae",
    keywords: [
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh mi",
      "banh mi ",
      "banh mi m",
      "banh mi ma",
      "banh mi mat",
      "banh mi mat ",
      "banh mi mat o",
      "banh mi mat on",
      "banh mi mat ong",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh mi",
      "banh mi ",
      "banh mi o",
      "banh mi on",
      "banh mi ong",
      "banh mi ong ",
      "banh mi ong m",
      "banh mi ong ma",
      "banh mi ong mat",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh ma",
      "banh mat",
      "banh mat ",
      "banh mat m",
      "banh mat mi",
      "banh mat mi ",
      "banh mat mi o",
      "banh mat mi on",
      "banh mat mi ong",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh ma",
      "banh mat",
      "banh mat ",
      "banh mat o",
      "banh mat on",
      "banh mat ong",
      "banh mat ong ",
      "banh mat ong m",
      "banh mat ong mi",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh o",
      "banh on",
      "banh ong",
      "banh ong ",
      "banh ong m",
      "banh ong mi",
      "banh ong mi ",
      "banh ong mi m",
      "banh ong mi ma",
      "banh ong mi mat",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh o",
      "banh on",
      "banh ong",
      "banh ong ",
      "banh ong m",
      "banh ong ma",
      "banh ong mat",
      "banh ong mat ",
      "banh ong mat m",
      "banh ong mat mi",
      "m",
      "mi",
      "mi ",
      "mi b",
      "mi ba",
      "mi ban",
      "mi banh",
      "mi banh ",
      "mi banh m",
      "mi banh ma",
      "mi banh mat",
      "mi banh mat ",
      "mi banh mat o",
      "mi banh mat on",
      "mi banh mat ong",
      "m",
      "mi",
      "mi ",
      "mi b",
      "mi ba",
      "mi ban",
      "mi banh",
      "mi banh ",
      "mi banh o",
      "mi banh on",
      "mi banh ong",
      "mi banh ong ",
      "mi banh ong m",
      "mi banh ong ma",
      "mi banh ong mat",
      "m",
      "mi",
      "mi ",
      "mi m",
      "mi ma",
      "mi mat",
      "mi mat ",
      "mi mat b",
      "mi mat ba",
      "mi mat ban",
      "mi mat banh",
      "mi mat banh ",
      "mi mat banh o",
      "mi mat banh on",
      "mi mat banh ong",
      "m",
      "mi",
      "mi ",
      "mi m",
      "mi ma",
      "mi mat",
      "mi mat ",
      "mi mat o",
      "mi mat on",
      "mi mat ong",
      "mi mat ong ",
      "mi mat ong b",
      "mi mat ong ba",
      "mi mat ong ban",
      "mi mat ong banh",
      "m",
      "mi",
      "mi ",
      "mi o",
      "mi on",
      "mi ong",
      "mi ong ",
      "mi ong b",
      "mi ong ba",
      "mi ong ban",
      "mi ong banh",
      "mi ong banh ",
      "mi ong banh m",
      "mi ong banh ma",
      "mi ong banh mat",
      "m",
      "mi",
      "mi ",
      "mi o",
      "mi on",
      "mi ong",
      "mi ong ",
      "mi ong m",
      "mi ong ma",
      "mi ong mat",
      "mi ong mat ",
      "mi ong mat b",
      "mi ong mat ba",
      "mi ong mat ban",
      "mi ong mat banh",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat b",
      "mat ba",
      "mat ban",
      "mat banh",
      "mat banh ",
      "mat banh m",
      "mat banh mi",
      "mat banh mi ",
      "mat banh mi o",
      "mat banh mi on",
      "mat banh mi ong",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat b",
      "mat ba",
      "mat ban",
      "mat banh",
      "mat banh ",
      "mat banh o",
      "mat banh on",
      "mat banh ong",
      "mat banh ong ",
      "mat banh ong m",
      "mat banh ong mi",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat m",
      "mat mi",
      "mat mi ",
      "mat mi b",
      "mat mi ba",
      "mat mi ban",
      "mat mi banh",
      "mat mi banh ",
      "mat mi banh o",
      "mat mi banh on",
      "mat mi banh ong",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat m",
      "mat mi",
      "mat mi ",
      "mat mi o",
      "mat mi on",
      "mat mi ong",
      "mat mi ong ",
      "mat mi ong b",
      "mat mi ong ba",
      "mat mi ong ban",
      "mat mi ong banh",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat o",
      "mat on",
      "mat ong",
      "mat ong ",
      "mat ong b",
      "mat ong ba",
      "mat ong ban",
      "mat ong banh",
      "mat ong banh ",
      "mat ong banh m",
      "mat ong banh mi",
      "m",
      "ma",
      "mat",
      "mat ",
      "mat o",
      "mat on",
      "mat ong",
      "mat ong ",
      "mat ong m",
      "mat ong mi",
      "mat ong mi ",
      "mat ong mi b",
      "mat ong mi ba",
      "mat ong mi ban",
      "mat ong mi banh",
      "o",
      "on",
      "ong",
      "ong ",
      "ong b",
      "ong ba",
      "ong ban",
      "ong banh",
      "ong banh ",
      "ong banh m",
      "ong banh mi",
      "ong banh mi ",
      "ong banh mi m",
      "ong banh mi ma",
      "ong banh mi mat",
      "o",
      "on",
      "ong",
      "ong ",
      "ong b",
      "ong ba",
      "ong ban",
      "ong banh",
      "ong banh ",
      "ong banh m",
      "ong banh ma",
      "ong banh mat",
      "ong banh mat ",
      "ong banh mat m",
      "ong banh mat mi",
      "o",
      "on",
      "ong",
      "ong ",
      "ong m",
      "ong mi",
      "ong mi ",
      "ong mi b",
      "ong mi ba",
      "ong mi ban",
      "ong mi banh",
      "ong mi banh ",
      "ong mi banh m",
      "ong mi banh ma",
      "ong mi banh mat",
      "o",
      "on",
      "ong",
      "ong ",
      "ong m",
      "ong mi",
      "ong mi ",
      "ong mi m",
      "ong mi ma",
      "ong mi mat",
      "ong mi mat ",
      "ong mi mat b",
      "ong mi mat ba",
      "ong mi mat ban",
      "ong mi mat banh",
      "o",
      "on",
      "ong",
      "ong ",
      "ong m",
      "ong ma",
      "ong mat",
      "ong mat ",
      "ong mat b",
      "ong mat ba",
      "ong mat ban",
      "ong mat banh",
      "ong mat banh ",
      "ong mat banh m",
      "ong mat banh mi",
      "o",
      "on",
      "ong",
      "ong ",
      "ong m",
      "ong ma",
      "ong mat",
      "ong mat ",
      "ong mat m",
      "ong mat mi",
      "ong mat mi ",
      "ong mat mi b",
      "ong mat mi ba",
      "ong mat mi ban",
      "ong mat mi banh",
    ],
  },
  {
    id: "pns9WODOmJTCpABZqDDo",
    description: "Nho trồng tại Úc",
    categoryId: "X63OeZXLKAqyVcAm38aT",
    discount: 10,
    unit: "g",
    quantity: 17,
    price: 27000,
    updatedDate: {
      seconds: 1626979048,
      nanoseconds: 331000000,
    },
    keywords: [
      "n",
      "nh",
      "nho",
      "nho ",
      "nho u",
      "nho uc",
      "u",
      "uc",
      "uc ",
      "uc n",
      "uc nh",
      "uc nho",
    ],
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/fr10.jpg?alt=media&token=2b8c53a1-36f6-4a3e-8650-27b9c7620c2d",
    rating: 4,
    createdDate: {
      seconds: 1626904238,
      nanoseconds: 625000000,
    },
    productName: "Nho Úc",
  },
  {
    id: "83SkWmDM53ZndxUKDXLg",
    discount: 20,
    createdDate: {
      seconds: 1626904179,
      nanoseconds: 503000000,
    },
    price: 47000,
    productName: "Khoai tây",
    description: "Truồng tự nhiên",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/v5.jpg?alt=media&token=32ae9292-9f2a-47fa-9ef2-e0a63265e930",
    updatedDate: {
      seconds: 1626977792,
      nanoseconds: 257000000,
    },
    rating: 4,
    quantity: 21,
    unit: "kg",
    categoryId: "Y4wlWVRg8AUjnGt8zjJC",
    keywords: [
      "k",
      "kh",
      "kho",
      "khoa",
      "khoai",
      "khoai ",
      "khoai t",
      "khoai ta",
      "khoai tay",
      "t",
      "ta",
      "tay",
      "tay ",
      "tay k",
      "tay kh",
      "tay kho",
      "tay khoa",
      "tay khoai",
    ],
  },
  {
    id: "VKW2FzZiI230S4egpBCN",
    quantity: 21,
    unit: "g",
    rating: 2,
    keywords: [
      "t",
      "th",
      "thi",
      "thit",
      "thit ",
      "thit l",
      "thit lo",
      "thit lon",
      "l",
      "lo",
      "lon",
      "lon ",
      "lon t",
      "lon th",
      "lon thi",
      "lon thit",
    ],
    productName: "Thịt lợn",
    description: "Thịt lợn rừng",
    createdDate: {
      seconds: 1626822617,
      nanoseconds: 953000000,
    },
    discount: 15,
    updatedDate: {
      seconds: 1626977812,
      nanoseconds: 723000000,
    },
    categoryId: "jqaq8roGL4QRZKn9Hpc7",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/meat4.jpg?alt=media&token=dbcba721-4ebf-4689-8418-d38036b055f0",
    price: 26000,
  },
  {
    id: "VyUcPwAPwZAGSXnkYJvK",
    price: 17000,
    discount: 10,
    keywords: [
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh m",
      "banh mi",
      "banh mi ",
      "banh mi b",
      "banh mi bo",
      "b",
      "ba",
      "ban",
      "banh",
      "banh ",
      "banh b",
      "banh bo",
      "banh bo ",
      "banh bo m",
      "banh bo mi",
      "m",
      "mi",
      "mi ",
      "mi b",
      "mi ba",
      "mi ban",
      "mi banh",
      "mi banh ",
      "mi banh b",
      "mi banh bo",
      "m",
      "mi",
      "mi ",
      "mi b",
      "mi bo",
      "mi bo ",
      "mi bo b",
      "mi bo ba",
      "mi bo ban",
      "mi bo banh",
      "b",
      "bo",
      "bo ",
      "bo b",
      "bo ba",
      "bo ban",
      "bo banh",
      "bo banh ",
      "bo banh m",
      "bo banh mi",
      "b",
      "bo",
      "bo ",
      "bo m",
      "bo mi",
      "bo mi ",
      "bo mi b",
      "bo mi ba",
      "bo mi ban",
      "bo mi banh",
    ],
    rating: 3,
    quantity: 27,
    unit: "Sản phẩm",
    productName: "Bánh mì bơ",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/b2.jpg?alt=media&token=f93c5b21-8e40-42dc-b09d-35918d314cbb",
    updatedDate: {
      seconds: 1626977842,
      nanoseconds: 632000000,
    },
    description: "Sản xuất trong ngày",
    categoryId: "ucZK9up2unneAdUkXNRn",
    createdDate: {
      seconds: 1626822101,
      nanoseconds: 265000000,
    },
  },
  {
    id: "2ImV7wmNLx6JzDitbTWG",
    categoryId: "X63OeZXLKAqyVcAm38aT",
    unit: "Quả",
    discount: 29,
    rating: 5,
    keywords: [
      "d",
      "du",
      "dua",
      "dua ",
      "dua h",
      "dua ha",
      "dua hau",
      "dua hau ",
      "dua hau m",
      "dua hau mi",
      "dua hau min",
      "d",
      "du",
      "dua",
      "dua ",
      "dua m",
      "dua mi",
      "dua min",
      "dua min ",
      "dua min h",
      "dua min ha",
      "dua min hau",
      "h",
      "ha",
      "hau",
      "hau ",
      "hau d",
      "hau du",
      "hau dua",
      "hau dua ",
      "hau dua m",
      "hau dua mi",
      "hau dua min",
      "h",
      "ha",
      "hau",
      "hau ",
      "hau m",
      "hau mi",
      "hau min",
      "hau min ",
      "hau min d",
      "hau min du",
      "hau min dua",
      "m",
      "mi",
      "min",
      "min ",
      "min d",
      "min du",
      "min dua",
      "min dua ",
      "min dua h",
      "min dua ha",
      "min dua hau",
      "m",
      "mi",
      "min",
      "min ",
      "min h",
      "min ha",
      "min hau",
      "min hau ",
      "min hau d",
      "min hau du",
      "min hau dua",
    ],
    quantity: 36,
    createdDate: {
      seconds: 1626821830,
      nanoseconds: 352000000,
    },
    description: "Dưa hấu Ninh Thuận",
    productImage:
      "https://firebasestorage.googleapis.com/v0/b/ecommerce-da802.appspot.com/o/fr2.jpg?alt=media&token=5f8a2d07-b526-49b8-a254-665015164760",
    updatedDate: {
      seconds: 1630121026,
      nanoseconds: 945000000,
    },
    productName: "Dưa hấu min",
    price: 12000,
  },
];
